// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
//NEW 2018 ROBOT CODE

package org.usfirst.frc.team6593.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc.team6593.robot.*;

/**
 *
 */
public class TankDrive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TankDrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	//Robot.driveTrain.GyroReset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Robot.driveTrain.tankdrive(-Robot.oi.getDriveLeftSpeed(), -Robot.oi.getDriveRightSpeed());
    	//Robot.driveTrain.tankdrive(Robot.oi.getDriveRightSpeed(), Robot.oi.getDriveLeftSpeed());
    	Robot.driveTrain.teleopGyroStraight(Robot.oi.xbox_Joystick);
    	//Robot.driveTrain.gyroDrive(Robot.oi.getDriveLeftSpeed(), Robot.oi.getDriveRightSpeed());
    	//Robot.driveTrain.teleopGyroRoate(Robot.oi.getDriveLeftSpeed(), Robot.oi.getDriveRightSpeed());
    	Robot.driveTrain.teleopGyroRoate(Robot.oi.xbox_Joystick.getY(), Robot.oi.xbox_Joystick.getZ());


    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
